name: kfb
description: Kolkata Fresh Bazaar Application

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.6+6

environment:
    sdk: ">=2.7.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    http: ^0.12.2
    woocommerce_api: ^0.0.9
    dio: ^3.0.9
    provider: ^4.3.1
    shared_preferences: ^0.5.8
    page_transition: ^1.1.5
    cached_network_image: ^2.2.0+1
    flutter_money_formatter: ^0.8.3
    pull_to_refresh: ^1.5.8
    auto_size_text: ^2.1.0
    # intl: ^0.16.1
    intl: ^0.15.8
    flutter_swiper: ^1.1.6
    razorpay_flutter: ^1.2.1
    edge_alert: ^0.0.1
    bubble_tab_indicator: ^0.1.4
    status_alert: ^0.1.2
    math_expressions: ^2.0.0
    flutter_spinkit: ^4.1.2+1
    html: ^0.14.0+3
    carousel_slider: ^2.1.0
    google_fonts: ^1.1.0
    wp_json_api: ^0.1.4
    package_info: ^0.4.0+16
    platform_alert_dialog: ^1.0.0+2
    rflutter_alert:
        git: git://github.com/RatelHub/rflutter_alert.git

    # The following adds the Cupertino Icons font to your application.
    # Use with the CupertinoIcons class for iOS style icons.
    cupertino_icons: ^0.1.3

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_launcher_icons: ^0.7.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/icon/appicon.png"

# The following section is specific to Flutter.
flutter:
    # The following line ensures that the Material Icons font is
    # included with your application, so that you can use the icons in
    # the material Icons class.
    uses-material-design: true
    # To add assets to your application, add an assets section, like this:
    assets:
        # - assets/images/close.png
        # - assets/images/3.0x/close.png
        # Banner Carousel Images
        - assets/images/slide_1.jpg
        - assets/images/slide_2.jpg
        - assets/images/slide_3.jpg
        - assets/images/slide_4.jpg
        - assets/images/slide_5.jpg
        - assets/images/slide_6.jpg

        - assets/images/shipping_icon.png
        - assets/images/cradit_cards.jpg

        - assets/images/razorpay.png
        - assets/images/popup_new.jpg
        - assets/images/splash_screen_new.gif

        # New Category Images
        - assets/images/cat1.jpg
        - assets/images/cat2.jpg
        - assets/images/cat3.jpg
        - assets/images/cat4.jpg
        - assets/images/cat5.jpg
        - assets/images/cat6.jpg
        - assets/images/cat7.jpg
        - assets/images/cat8.jpg
        - assets/images/cat9.jpg
        - assets/images/cat10.jpg
        - assets/images/cat11.jpg

        # Banner Images
        - assets/images/banner_1.jpg
        - assets/images/banner_2.jpg
        - assets/images/banner_3.jpg
    #   - images/a_dot_ham.jpeg
    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.
    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages
    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    fonts:
        - family: Nunito
          fonts:
              - asset: assets/fonts/Nunito-SemiBold.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
